import logging

__all__ = ["generate_rollout", "episode_reward_from_sample"]

logger = logging.getLogger(__name__)


TOKENIZER = None
PROCESSOR = None
MASK_GENERATOR = None
SAMPLE_PRINTED = False


def episode_reward_from_sample(sample) -> float:
    """Scalar episode target from JSONL `reward`, metadata, or `label`."""
    reward = sample.reward
    if isinstance(reward, dict):
        for key in ("reward", "score"):
            if key in reward:
                reward = reward[key]
                break
    if reward is None:
        reward = (sample.metadata or {}).get("reward")
    if reward is None and sample.label is not None:
        reward = sample.label
    if isinstance(reward, bool):
        return float(reward)
    if isinstance(reward, (int, float)):
        parsed = float(reward)
        if parsed == parsed:
            return parsed
        raise ValueError(f"value-pretrain sample has NaN reward: {sample!r}")
    if isinstance(reward, str):
        parsed = float(reward)
        if parsed == parsed:
            return parsed
        raise ValueError(f"value-pretrain sample has NaN reward label: {sample!r}")
    raise ValueError(f"value-pretrain sample missing finite reward: {sample!r}")


def generate_rollout(args, rollout_id, data_buffer, evaluation=False):
    """File-backed rollout for `--value-pretrain`: tokenize like SFT, keep the episode reward.

    Args:
        args: the whole args
        rollout_id: int, the id of the rollout, used for deterministic data generation
        data_buffer: the data buffer to store the generated samples
        evaluation: bool, whether the rollout is for evaluation or not

    Returns:
        list[Sample]: a list of samples generated by the rollout
    """
    assert not evaluation
    assert args.rollout_global_dataset

    from miles.utils.mask_utils import MultiTurnLossMaskGenerator
    from miles.utils.processing_utils import load_processor, load_tokenizer

    global TOKENIZER, PROCESSOR, MASK_GENERATOR, SAMPLE_PRINTED
    if TOKENIZER is None:
        TOKENIZER = load_tokenizer(
            args.hf_checkpoint, chat_template_path=args.chat_template_path, trust_remote_code=True
        )

    if PROCESSOR is None:
        PROCESSOR = load_processor(args.hf_checkpoint, trust_remote_code=True)

    if MASK_GENERATOR is None:
        MASK_GENERATOR = MultiTurnLossMaskGenerator(TOKENIZER, tokenizer_type=args.loss_mask_type)

    samples = data_buffer.get_samples(args.rollout_batch_size)

    for i, sample in enumerate(samples):
        (sample,) = sample
        messages = sample.prompt
        tools = sample.metadata.get("tools", None)

        token_ids, loss_mask = MASK_GENERATOR.get_loss_mask(messages, tools=tools)

        response_length = MASK_GENERATOR.get_response_lengths([loss_mask])[0]

        sample.tokens = token_ids
        sample.response_length = response_length
        sample.reward = episode_reward_from_sample(sample)
        sample.loss_mask = loss_mask[-response_length:]

        if i == 0 and not SAMPLE_PRINTED:
            print(
                f"@dhawgupta: value_pretrain_rollout reward={sample.reward} "
                f"response_length={response_length}",
                flush=True,
            )
            logger.info(
                f"value_pretrain_rollout::generate_rollout example data: {sample=} "
                f"(raw){messages=} (raw){token_ids=} (raw){loss_mask=} {response_length=}"
            )
            SAMPLE_PRINTED = True

    return samples
